// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AES_Encrypt (
unsigned char plaintext[16],
unsigned char expandedKey[176],
unsigned short Nr,
unsigned char ciphertext[16]);
