// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xaes_encrypt.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAes_encrypt_CfgInitialize(XAes_encrypt *InstancePtr, XAes_encrypt_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtlsc_BaseAddress = ConfigPtr->Crtlsc_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAes_encrypt_Start(XAes_encrypt *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_encrypt_ReadReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_AP_CTRL) & 0x80;
    XAes_encrypt_WriteReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_AP_CTRL, Data | 0x01);
}

u32 XAes_encrypt_IsDone(XAes_encrypt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_encrypt_ReadReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XAes_encrypt_IsIdle(XAes_encrypt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_encrypt_ReadReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XAes_encrypt_IsReady(XAes_encrypt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_encrypt_ReadReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XAes_encrypt_EnableAutoRestart(XAes_encrypt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_encrypt_WriteReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_AP_CTRL, 0x80);
}

void XAes_encrypt_DisableAutoRestart(XAes_encrypt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_encrypt_WriteReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_AP_CTRL, 0);
}

void XAes_encrypt_Set_Nr(XAes_encrypt *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_encrypt_WriteReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_NR_DATA, Data);
}

u32 XAes_encrypt_Get_Nr(XAes_encrypt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes_encrypt_ReadReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_NR_DATA);
    return Data;
}

u32 XAes_encrypt_Get_newState_BaseAddress(XAes_encrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Crtlsc_BaseAddress + XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_BASE);
}

u32 XAes_encrypt_Get_newState_HighAddress(XAes_encrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Crtlsc_BaseAddress + XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_HIGH);
}

u32 XAes_encrypt_Get_newState_TotalBytes(XAes_encrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_HIGH - XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_BASE + 1);
}

u32 XAes_encrypt_Get_newState_BitWidth(XAes_encrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAES_ENCRYPT_CRTLSC_WIDTH_NEWSTATE;
}

u32 XAes_encrypt_Get_newState_Depth(XAes_encrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAES_ENCRYPT_CRTLSC_DEPTH_NEWSTATE;
}

u32 XAes_encrypt_Write_newState_Words(XAes_encrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_HIGH - XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Crtlsc_BaseAddress + XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XAes_encrypt_Read_newState_Words(XAes_encrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_HIGH - XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Crtlsc_BaseAddress + XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_BASE + (offset + i)*4);
    }
    return length;
}

u32 XAes_encrypt_Write_newState_Bytes(XAes_encrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_HIGH - XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Crtlsc_BaseAddress + XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XAes_encrypt_Read_newState_Bytes(XAes_encrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_HIGH - XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Crtlsc_BaseAddress + XAES_ENCRYPT_CRTLSC_ADDR_NEWSTATE_BASE + offset + i);
    }
    return length;
}

u32 XAes_encrypt_Get_expandedKey_BaseAddress(XAes_encrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Crtlsc_BaseAddress + XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_BASE);
}

u32 XAes_encrypt_Get_expandedKey_HighAddress(XAes_encrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Crtlsc_BaseAddress + XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_HIGH);
}

u32 XAes_encrypt_Get_expandedKey_TotalBytes(XAes_encrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_HIGH - XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_BASE + 1);
}

u32 XAes_encrypt_Get_expandedKey_BitWidth(XAes_encrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAES_ENCRYPT_CRTLSC_WIDTH_EXPANDEDKEY;
}

u32 XAes_encrypt_Get_expandedKey_Depth(XAes_encrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAES_ENCRYPT_CRTLSC_DEPTH_EXPANDEDKEY;
}

u32 XAes_encrypt_Write_expandedKey_Words(XAes_encrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_HIGH - XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Crtlsc_BaseAddress + XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XAes_encrypt_Read_expandedKey_Words(XAes_encrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_HIGH - XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Crtlsc_BaseAddress + XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_BASE + (offset + i)*4);
    }
    return length;
}

u32 XAes_encrypt_Write_expandedKey_Bytes(XAes_encrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_HIGH - XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Crtlsc_BaseAddress + XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XAes_encrypt_Read_expandedKey_Bytes(XAes_encrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_HIGH - XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Crtlsc_BaseAddress + XAES_ENCRYPT_CRTLSC_ADDR_EXPANDEDKEY_BASE + offset + i);
    }
    return length;
}

void XAes_encrypt_InterruptGlobalEnable(XAes_encrypt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_encrypt_WriteReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_GIE, 1);
}

void XAes_encrypt_InterruptGlobalDisable(XAes_encrypt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_encrypt_WriteReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_GIE, 0);
}

void XAes_encrypt_InterruptEnable(XAes_encrypt *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAes_encrypt_ReadReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_IER);
    XAes_encrypt_WriteReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_IER, Register | Mask);
}

void XAes_encrypt_InterruptDisable(XAes_encrypt *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAes_encrypt_ReadReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_IER);
    XAes_encrypt_WriteReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_IER, Register & (~Mask));
}

void XAes_encrypt_InterruptClear(XAes_encrypt *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes_encrypt_WriteReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_ISR, Mask);
}

u32 XAes_encrypt_InterruptGetEnabled(XAes_encrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAes_encrypt_ReadReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_IER);
}

u32 XAes_encrypt_InterruptGetStatus(XAes_encrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAes_encrypt_ReadReg(InstancePtr->Crtlsc_BaseAddress, XAES_ENCRYPT_CRTLSC_ADDR_ISR);
}

